### PR TITLE
Syntax error checks for the web frontend

### PR DESCRIPTION
**Pull request by askuri**
Kindly review this locally as well please. I tested it but I have missed something.

### CODE REVIEW

**Comment by LhKipp** [comment]
Hey,

I just checked out your work. I got some problems making it work :(

```shell
[I] [~/Code/prolog_bfs]$ rm CMakeCache.txt 
[I] [~/Code/prolog_bfs]$ rm CMakeFiles/ -rf
[I] [~/Code/prolog_bfs]$ ./build_wasm.sh 
error: use `emcmake` rather then `emconfigure` for cmake projects
make: make prolog_bfs
-- The C compiler identification is Clang 11.0.0
-- The CXX compiler identification is Clang 11.0.0
-- Check for working C compiler: /home/leonhard/Programs/emsdk/upstream/emscripten/emcc
-- Check for working C compiler: /home/leonhard/Programs/emsdk/upstream/emscripten/emcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/leonhard/Programs/emsdk/upstream/emscripten/em++
-- Check for working CXX compiler: /home/leonhard/Programs/emsdk/upstream/emscripten/em++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/leonhard/Code/prolog_bfs
Scanning dependencies of target prolog_bfs
[  8%] Building CXX object CMakeFiles/prolog_bfs.dir/src/wam/bfs_organizer/bfs_organizer.cpp.o
[ 16%] Building CXX object CMakeFiles/prolog_bfs.dir/src/wam/bfs_organizer/util/read_program_code.cpp.o
[ 25%] Building CXX object CMakeFiles/prolog_bfs.dir/src/wam/bfs_organizer/util/substitution_util.cpp.o
[ 33%] Building CXX object CMakeFiles/prolog_bfs.dir/src/wam/compiler/compiler.cpp.o
[ 41%] Building CXX object CMakeFiles/prolog_bfs.dir/src/wam/compiler/parser/util.cpp.o
[ 50%] Building CXX object CMakeFiles/prolog_bfs.dir/src/wam/data/var_substitution.cpp.o
[ 58%] Building CXX object CMakeFiles/prolog_bfs.dir/src/wam/executor/executor.cpp.o
[ 66%] Building CXX object CMakeFiles/prolog_bfs.dir/src/wam/instructions/instructions.cpp.o
[ 75%] Building CXX object CMakeFiles/prolog_bfs.dir/src/wam/instructions/util/instructions_util.cpp.o
[ 83%] Building CXX object CMakeFiles/prolog_bfs.dir/src/wasm/parser_error_binding.cpp.o
[ 91%] Building CXX object CMakeFiles/prolog_bfs.dir/src/wasm/wasm.cpp.o
[100%] Linking CXX executable build/prolog_bfs
shared:WARNING: Assuming object file output in the absence of `-c`, based on output filename. Please add with `-c` or `-r` to avoid this warning
[100%] Built target prolog_bfs
[I] [~/Code/prolog_bfs]$ ./start_server.sh 
Web server root directory: /home/leonhard/Code/prolog_bfs/web
Now listening at http://localhost:8080/
localhost - - [08/Mar/2020 19:58:30] code 404, message File not found: /home/leonhard/Code/prolog_bfs/web/build/prolog_bfs.js
localhost - - [08/Mar/2020 19:58:30] "GET /build/prolog_bfs.js HTTP/1.1" 404 -
localhost - - [08/Mar/2020 19:58:30] code 404, message File not found: /home/leonhard/Code/prolog_bfs/web/build/prolog_bfs.js
localhost - - [08/Mar/2020 19:58:30] "GET /build/prolog_bfs.js HTTP/1.1" 404 -
```

Looks like executable gets saved as "prolog_bfs" in web/build? But if I do 
```shell
[I] [~/Code/prolog_bfs]$ mv web/build/prolog_bfs web/build/prolog_bfs.js
[I] [~/Code/prolog_bfs]$ ./start_server.sh 
Web server root directory: /home/leonhard/Code/prolog_bfs/web
Now listening at http://localhost:8080/
```
The developer console will scream at me:
image

Any clues?

In "start_server.sh" is also a path hardcoded. I dont think the instruction should be there at all.

**Comment by askuri** [comment]
I tried to build it again and it worked fine. I also don't get the warning about missing -c parameter. Please try deleting CMakeFiles, build folder and CMakeCache.txt.

If that doesn't work, please send me your output of emcc -v

> In "start_server.sh" is also a path hardcoded. I dont think the instruction should be there at all.
Indeed, I should remove that path as it will only work on my system anyway. Just source the environment like if you're running the build script as usual.

**Comment by LhKipp** [comment]
Okay. The error is on my end.
I've tried to compile this PR and the master branch with:
```shell
[I] [~/Code/prolog_bfs]$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.9
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 7202d9cde9d23ba94c7f09fd6b5eafc437136542)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/leonhard/Programs/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)

[I] [~/Code/prolog_bfs]$ cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
Both times were without success.

Can you please post your versions? I will update then accordingly.

**Comment by askuri** [comment]
```
$ emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.39.8
clang version 11.0.0 (/b/s/w/ir/cache/git/chromium.googlesource.com-external-github.com-llvm-llvm--project 9dc84e9b02d1e402503906099d42fbae4da7d8d9)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/martin/Apps/emsdk/upstream/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64
shared:INFO: (Emscripten: Running sanity checks)

$ cmake --version
cmake version 3.13.4
```

**Comment by LhKipp** [comment]
Good Work

**Pull request merged**
